name-template: v$NEXT_PATCH_VERSION
categories:
  - title: Features
    label: feature
  - title: Bug Fixes
    label: bug
  - title: Maintenance
    label: maintenance
tag-template: - $TITLE @$AUTHOR (#$NUMBER)
template: |
  ## Changes

  $CHANGES
